export const selectTipoColaborador = [
    { value: 1, descripcion: "Discapacitado" },
    { value: 2, descripcion: "Sustituto" },
    { value: 0, descripcion: "No aplica" },
  ];

export const  ciudadesEcuador = [
    "Quito",
    "Guayaquil",
    "Cuenca",
    "Ambato",
    "Manta",
    "Loja",
    "Portoviejo",
    "Esmeraldas",
    "Ibarra",
    "Machala",
    "Santo Domingo de los Colorados",
    "Quevedo",
    "Riobamba",
    "Tulcán",
    "Latacunga",
    "Milagro",
    "Santa Elena",
    "Zamora",
    "La Libertad",
    "Sangolquí",
    "Nueva Loja",
    "Babahoyo",
    "Azogues",
    "Huaquillas",
    "Chone",
    "Jipijapa",
    "Puerto Francisco de Orellana",
    "Vinces",
    "Montecristi",
    "Yaguachi",
    "Tena",
    "La Troncal",
    "Balzar",
    "Pinas",
    "Boca Suno",
    "El Triunfo",
    "Catamayo",
    "Guaranda",
    "Pedro Carbo",
    "Macas",
    "Calceta",
    "Santa Rosa",
    "Cayambe",
    "Puyo",
    "Sucre",
    "San Miguel de los Bancos",
    "Salinas",
    "Jaramijó",
    "San Gabriel",
    "Gualaceo",
    "La Mana",
    "Pujilí",
    "Samborondón",
    "Cotacachi",
    "Machachi",
    "Puerto Ayora",
    "Banos de Agua Santa",
    "Ambuquí",
    "Alausí",
    "San Lorenzo",
    "Tosagua",
    "Catarama",
    "Chordeleg",
    "Tosagua",
    "Alfredo Baquerizo Moreno",
    "San Vicente",
    "Cariamanga",
    "Pillaro",
    "Santa Ana",
    "Lomas de Sargentillo",
    "Paute",
    "San Cristóbal",
    "Zaruma",
    "Cayambe",
    "Caluma",
    "Buena Fe",
    "San Miguel",
    "Piñas",
    "Olmedo",
    "Pedernales",
    "Santo Domingo de los Tsáchilas",
    "Puerto Bolívar",
    "Durán",
    "Naranjito",
    "El Empalme",
    "Pajan",
    "San Juan Bosco",
    "Colimes",
    "Quinsaloma",
    "La Concordia",
  ];
