# Node.js with Angular

# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- Release

pool:
  vmImage: windows-latest

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '12.22.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install -g @angular/cli@11.2.14'
  displayName: 'Angular CLI'

- task: Npm@1
  inputs:
    command: 'ci'
  displayName: NPM Install Dependencies
  
- task: Npm@1
  timeoutInMinutes: 120
  inputs:
    command: 'custom'
    customCommand: 'run build'
  displayName: 'Build Prod'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)\dist\vex'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: true
  displayName: 'Save Artifact'
 
## Generamos el artefacto para publicar en produccion
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'EasyFCPC-Backoffice'
    publishLocation: 'Container'
    Parallel: false
  displayName: 'Publish Artifact'